version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - config_dev_secrets.env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network
  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    env_file:
      - config_dev_secrets.env
    ports:
      - 16543:80
    networks:
      - postgres-db-network

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data
networks:
  postgres-db-network:
    driver: bridge