version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dash-api-network
  #--------------------------------
  #
  #--------------------------------
  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@stablecaps.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 6543:80
    depends_on:
      - postgres
    networks:
      - dash-api-network
  #--------------------------------
  #
  #--------------------------------
  # dashboardapi:
  #   container_name: dashboardapi
  #   image: dashboardapi:1.0.0
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.RestAPI
  #   env_file:
  #     - ./config_dev_secrets.env
  #   volumes:
  #     - postgres-db-volume:/var/lib/postgresql/data:rw
  #   ports:
  #     - 969:8969
  #   depends_on:
  #     - postgres
  #   networks:
  #     - dash-api-network
#--------------------------------
#
#--------------------------------
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data
#--------------------------------
#
#--------------------------------
networks:
  dash-api-network:
    driver: bridge